# Funding options for LiquidGlass
# This file allows users to sponsor your project directly from GitHub

# github: xnxjoe
# patreon: your-patreon
# ko_fi: your-kofi
# custom: ["https://yourwebsite.com/donate", "Donate via PayPal"]
